#! /bin/bash

# Copyright(c) 2012 Francesco Strozzi <francesco.strozzi@gmail.com>
#
# Simple tool to initialize a new Scala project
#
#
echo -e "\nSTBX: Simple Scala Toolbox for project initialization.\n"

command -v sbt >/dev/null 2>&1 || { echo >&2 "SBT not installed or not in PATH.  Please install SBT"; exit 1; }
command -v git >/dev/null 2>&1 || { echo >&2 "GIT not installed or not in PATH. Please install GIT"; exit 1; }
command -v java >/dev/null 2>&1 || { echo >&2 "JAVA not installed or not in PATH. Please install JAVA"; exit 1; }

if [ -z "$1" ]; then
	echo "Please supply a project name"
	exit
fi
if [ -d "$1" ]; then
	echo "Directory $1 already exists!"
	exit
fi
name=$1
mkdir $name
cd $name

echo "Creating the new project $name..."
mkdir -p src/{main,test}/{scala,java,resources}
mkdir -p project

echo -e "

import AssemblyKeys._ 

assemblySettings

name := \"$name\"


version := \"1.0\"

//libraryDependencies ++= Seq(
//	groupID % artifactID % revision,
//	groupID % otherID % otherRevision
//)

//resolvers += \"Sonatype OSS Snapshots\" at \"https://oss.sonatype.org/content/repositories/snapshots\"
				
" > build.sbt
echo "Done."

echo -e "

addSbtPlugin(\"com.eed3si9n\" % \"sbt-assembly\" % \"0.8.6\")

" > project/plugins.sbt

git init
echo "target/" >> .gitignore

echo "Running SBT on the project..."
sbt
